public with sharing class Constants {
    public static final String MEETUP_STATUS_CLOSED = 'Closed';
    public static final String MEETUP_STATUS_OPENED = 'Open';
    public static final String MEETUP_CLOSED_ERROR = 'Registration failed because the Meetup has reached the registration limit.';
    public static final String MEETUP_EMAIL_ERROR = 'The provided email address has already been registered with the meetup.';
}
